### ISSUE TITLE
add `is_available` a boolean to know if we're using the `nop` version or the `default` version

### ISSUE THREAD

**Issue by zapashcanon** [formalsec/smtml#149]
For instance, it would allow to do something like:

```ocaml
let solver =
  if Z3_mappings.is_available then Ok Z3_mappings
  else if Colibri2_mappings.is_available then Ok Colibri2
  else if ...
  else Error (`Msg "no available solver")
```

It would be useful for instance to try many solvers when the user didn't specified one in Owi - instead of only trying Z3 and to fail if it's not there.

The implementation is quite straightforward (add `let is_available = false` to the `nop` file and `let is_available = true` in all `default` implementations).

**Comment by filipeom** [comment]
Will do :smiley: 

Also, would having a function to enumerate available solvers be helpful? Something like `available_solvers : unit -> (solver_type list, string) result`.

**Comment by zapashcanon** [comment]
Indeed, that may be useful too. It can probably be a simple list btw `val available_solvers : solver_type list`.
