### ISSUE TITLE
Fix smtcomp parsing errors

### ISSUE THREAD

**Issue by filipeom** [formalsec/smtml#218]

**Comment by joaomhmpereira** [comment]
Logs for parsing errors:
[exceptions_FP.log](https://github.com/user-attachments/files/17165144/exceptions_FP.log)
[exceptions_LIA.log](https://github.com/user-attachments/files/17165145/exceptions_LIA.log)
[exceptions_S.log](https://github.com/user-attachments/files/17165146/exceptions_S.log)
