### ISSUE TITLE
Allow Z3 mappings to create contexts without models

### ISSUE THREAD

**Issue by filipeom** [formalsec/smtml#31]
During symbolic executions, contexts without models are slightly faster than when this option is enabled. Models are only used for test-suite generation at the end of the analysis, accounting for only a fraction of the executed queries.

**Comment by zapashcanon** [comment]
IIRC @chambart tried this and it was not making it any faster

**Comment by filipeom** [comment]
I tested it as well, and it doesn't appear to have any impact. However, Z3 consistently generates models, whether you set the 'model' option to 'true' or 'false,' so I may be overlooking something

**Comment by zapashcanon** [comment]
Yes, or Z3 may be completely ignoring this option

**Comment by filipeom** [comment]
It could be, I'll take a look into it :smile:

**Comment by filipeom** [comment]
This works, but Z3 is weird when you set model completion to true (set [here](https://github.com/formalsec/smtml/blob/feefe1fcd35f63119e4944c434d8ed9e22a9cced/lib/z3_mappings.default.ml#L760)). It still attempts to give an assignment for some symbols; however, this assignment might not be consistent with the conditions asserted in the solver.
