### ISSUE TITLE
Add remaining cases to Expr simplification

### ISSUE THREAD

**Issue by filipeom** [formalsec/smtml#60]
Related to OCamlPro/owi#122

**Comment by krtab** [comment]
I'm working on it

**Comment by filipeom** [comment]
```
(assert
  (f32.gt
    (f32.reinterpret_int
      (i32.reinterpret_float
        (f32.div
          (f32.reinterpret_int (i32.reinterpret_float symbol_0))
          (f32 2.))))
    (f32 0.)))
```

Case: f32.reinterpret_int (i32.reinterpret_float symbol_0) = symbol_0

**Comment by filipeom** [comment]
(f32.sub 
          (f32.sub 
            (f32 0.) 
            (f32.reinterpret_int (i32.reinterpret_float symbol_0))) 
          (f32 0.))))
`<expr> - 0. = <expr>`
