### ISSUE TITLE
Bring ECMA-SL's concrete evaluation to encoding

### ISSUE THREAD

**Issue by filipeom** [formalsec/smtml#99]
Needed in order to allow for the completion of formalsec/ECMA-SL#20

- :ballot_box_with_check: Exists
- :x: TODO
- :no_entry: Will not support 
- :exclamation: Might exist, needs verification
- :question: Don't know yet, don't add for now

## Unary

| Operators | Status | New Name |
|-----------|--------|----------|
| Typeof | :no_entry:  |
| Neg | :ballot_box_with_check: |
| BitwiseNot | :ballot_box_with_check: |
| LogicalNot | :ballot_box_with_check: |
| IntToFloat | :ballot_box_with_check:  |
| IntToString | :ballot_box_with_check: |
| IntToFourHex | :no_entry:  |
| OctalToDecimal | :no_entry:  |
| FloatToInt | :ballot_box_with_check:   |
| FloatToString | :ballot_box_with_check:   |
| ToInt | :no_entry:  |
| ToInt32 | :no_entry:  |
| ToUint16 | :no_entry:  |
| ToUint32 | :no_entry:  |
| IsNaN | :ballot_box_with_check: |
| StringToInt  | :ballot_box_with_check: |
| StringToFloat | :ballot_box_with_check:  |
| FromCharCode | :ballot_box_with_check: |
| FromCharCodeU | :no_entry:  |
| ToCharCode | :ballot_box_with_check: |
| ToCharCodeU | :no_entry:  |
| ToLowerCase | :no_entry:  |
| ToUpperCase | :no_entry:  |
| Trim | :ballot_box_with_check: |
| StringLen | :ballot_box_with_check: | Length |
| StringLenU | :no_entry:  |
| StringConcat | :ballot_box_with_check: |
| ObjectToList | :no_entry:  |
| ObjectFields | :no_entry:  |
| ArrayLen | :no_entry:  |
| ListToArray | :no_entry:  |
| ListHead | :x:  | Head |
| ListTail | :x:   | Tail |
| ListLen | :x:  | Length | 
| ListSort | :no_entry:   |
| ListReverse | :x:   | Reverse |
| ListRemoveLast | :no_entry:  |
| TupleFirst | :x:  | Head |
| TupleSecond | :x:  | Tail |
| TupleLen | :x: | Length |
| FloatToByte | :no_entry:  |
| Float32ToLEBytes | :no_entry:  |
| Float32ToBEBytes | :no_entry:  |
| Float64ToLEBytes | :no_entry:  |
| Float64ToBEBytes | :no_entry:  |
| Float32FromLEBytes | :no_entry:  |
| Float32FromBEBytes | :no_entry:  |
| Float64FromLEBytes | :no_entry:  |
| Float64FromBEBytes | :no_entry:  |
| BytesToString | :no_entry:  |
| Random | :no_entry:  |
| Abs | :ballot_box_with_check: |
| Sqrt | :ballot_box_with_check: |
| Ceil | :ballot_box_with_check: |
| Floor | :ballot_box_with_check: |
| Trunc | :ballot_box_with_check: |
| Exp | :ballot_box_with_check: |
| Log2 | :no_entry:  |
| LogE | :no_entry:  |
| Log10 | :no_entry:  |
| Sin | :no_entry:  |
| Cos | :no_entry:  |
| Tan | :no_entry:  |
| Sinh | :no_entry:  |
| Cosh | :no_entry:  |
| Tanh | :no_entry:  |
| Asin | :no_entry:  |
| Acos | :no_entry:  |
| Atan | :no_entry:  |
| Utf8Decode | :no_entry:  |
| HexDecode | :no_entry:  |
| ParseNumber | :no_entry:  |
| ParseString | :no_entry:  |
| ParseDate | :no_entry:  |

## Binary

| Operator | Status | New Name |
|----------|--------|----------|
| Plus | :ballot_box_with_check: |
| Minus | :ballot_box_with_check: |
| Times | :ballot_box_with_check: |
| Div | :ballot_box_with_check: |
| Modulo | :ballot_box_with_check: |
| Pow | :ballot_box_with_check: |
| BitwiseAnd | :ballot_box_with_check: |
| BitwiseOr | :ballot_box_with_check: |
| BitwiseXor | :ballot_box_with_check: |
| ShiftLeft | :ballot_box_with_check: |
| ShiftRight | :ballot_box_with_check: |
| ShiftRightLogical | :ballot_box_with_check: |
| LogicalAnd | :ballot_box_with_check: |
| LogicalOr | :ballot_box_with_check: |
| SCLogicalAnd | :ballot_box_with_check: |
| SCLogicalOr | :ballot_box_with_check: |
| Eq | :ballot_box_with_check: |
| NE | :ballot_box_with_check: |
| Lt | :ballot_box_with_check: |
| Gt | :ballot_box_with_check: |
| Le | :ballot_box_with_check: |
| Ge | :ballot_box_with_check: |
| ToPrecision | :no_entry:  |
| ToExponential | :no_entry:  |
| ToFixed | :no_entry:  |
| ObjectMem | :no_entry:  |
| StringNth | :ballot_box_with_check: |
| StringNthU | :no_entry:  |
| StringSplit | :no_entry:  |
| ArrayMake | :no_entry:  |
| ArrayNth | :no_entry:  |
| ListMem | :no_entry:  |
| ListNth | :x:  | At |
| ListAdd | :x: | List_append_last | 
| ListPrepend | :x: | List_append |
| ListConcat | :x:  | Concat |
| ListRemove | :no_entry:   |
| ListRemoveNth | :no_entry:   |
| TupleNth | :x: | At |
| IntToBEBytes | :no_entry:  |
| IntFromLEBytes | :no_entry: |
| UintFromLEBytes | :no_entry:  |
| Min | :ballot_box_with_check: |
| Max | :ballot_box_with_check: |
| Atan2 | :no_entry:  |

## Ternary

| Operator | Status | New Name |
|----------|--------|----------|
| ITE | :ballot_box_with_check: |
| StringSubstr | :ballot_box_with_check: |
| StringSubstrU | :no_entry:  |
| ArraySet | :no_entry:  |
| ListSet | :x:  | List_set |

## N-Ary

| Operator | Status |
|----------|--------|
| NAryLogicalAnd | :no_entry:  |
| NAryLogicalOr | :no_entry:  |
| ArrayExpr | :ballot_box_with_check: |
| ListExpr | :ballot_box_with_check: |
| TupleExpr | :ballot_box_with_check: |

**Comment by joaomhmpereira** [comment]
## Operators needed
### Strings
Unops
- [ ] ToLowerCase
- [ ] ToUpperCase
- [ ] ToFloat
- [ ] FromCharCode
- [ ] FromCharCodeU
- [ ] ToInt
- [ ] Trim
- [ ] StringLen
- [ ] StringLenU
- [ ] StringConcat

Binops
- [ ] StringSplit
- [ ] StringNth
- [ ] StringNthU

Triops
- [ ] StringSubstr
- [ ] StringSubstrU 

### Floats
Unops
- [ ] ToString
- [ ] IsNan
- [ ] ToInt
- [ ] ToUint32
- [ ] ToInt32
- [ ] ToUint16

Binops
- [ ] ToPrecision
- [ ] ToExponential
- [ ] ToFixed
